apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/SitaramKanagala/devops-rubyonrails.git
      type: git
      usernameSecret:
        name: github-secret
        key: username
      passwordSecret:
        name: github-secret
        key: password

  clusters: |
    - name: in-cluster
      server: https://kubernetes.default.svc
      config:
        bearerTokenSecret:
          name: argocd-token
          key: token
