apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
data:
  github-username: U2l0YXJhbUthbmFnYWxh
  github-token: Z2l0aHViX3BhdF8xMUJNWE9XTEEwVU1LQjk1MkdIQ3NMX0R1eE9MT1h3dENHUGUxNEt3ejJoeUJoa2lpMEpPT0c2SnpCZ0xsNVV2WHdGUFRUTDdXN2htNDY0WGFs
