# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_app_name_production
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    command: rails server -b 0.0.0.0
    depends_on:
      - db
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres@db/your_app_name_production

volumes:
  pg_data:

secrets:
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_HOST:
    external: true
